/*
 ******************************************************************************
 This file is part of MattRaffelNetCode.

    MattRaffelNetCode is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    MattRaffelNetCode is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with MattRaffelNetCode; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


    architected and written by 
    matt raffel 
    matt.raffel@mindspring.com

       copyright (c) 2007 by matt raffel unless noted otherwise

 ******************************************************************************
*/
#region using statements
using System;
using System.Collections.Generic;
using System.Text;
using System.Configuration;
using MattRaffelNetCode.Apps.SqlCodeGen;
#endregion
namespace MattRaffelNetCode.Apps.SqlCodeGen.Properties
{
    /// <summary>
    /// Custom code for the Settings class, which is partially autogenerated by visual studio
    /// </summary>
    internal sealed partial class Settings 
    {
        [UserScopedSetting()]
        public TemplateDataCollection Templates
        {
            get { return (TemplateDataCollection)this["Templates"]; }
            set { this["Templates"] = value; }
        }
    }
}
